In [7]:
import pandas as pd
file_path = '02_03_01_P_동물병원.xlsx'
df = pd.read_excel(file_path)
df

/opt/conda/lib/python3.10/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,번호,개방서비스명,개방서비스아이디,개방자치단체코드,관리번호,인허가일자,인허가취소일자,영업상태구분코드,영업상태명,상세영업상태코드,...,최종수정시점,데이터갱신구분,데이터갱신일자,업태구분명,좌표정보(X),좌표정보(Y),업무구분명,상세업무구분명,권리주체일련번호,총직원수
0,1,동물병원,02_03_01_P,4060000,406000001020230006,2023-12-07,NaN,1,영업/정상,0000,...,2023-12-07 09:35:57,I,2023-12-09 00:16:53,NaN,180417.472296,472842.218128,동물병원,NaN,000,0.0
1,2,동물병원,02_03_01_P,4950000,495000001020230001,2023-12-07,NaN,1,영업/정상,0000,...,2023-12-07 20:08:57,I,2023-12-09 00:16:53,NaN,154144.986025,150618.256486,동물병원,NaN,000,0.0
2,3,동물병원,02_03_01_P,4070000,407000001020230004,2023-12-06,NaN,1,영업/정상,0000,...,2023-12-06 17:45:48,I,2023-12-09 00:16:53,NaN,240579.939547,421811.035501,동물병원,NaN,000,0.0
3,4,동물병원,02_03_01_P,3980000,398000001020230002,2023-12-05,NaN,1,영업/정상,0000,...,2023-12-05 18:26:25,I,2023-12-07 00:17:04,NaN,212914.182432,454859.664256,동물병원,NaN,L00,0.0
4,5,동물병원,02_03_01_P,4040000,404000001020230004,2023-12-04,NaN,1,영업/정상,0000,...,2023-12-04 17:57:48,I,2023-12-06 00:17:03,NaN,213842.911220,442798.493856,동물병원,NaN,000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5131,5132,동물병원,02_03_01_P,5450000,545000001020020002,1964-05-02,NaN,1,영업/정상,0000,...,2019-01-15 09:36:32,U,2019-01-17 02:40:00,NaN,276362.969465,197878.597266,동물병원,NaN,000,NaN
5132,5133,동물병원,02_03_01_P,4680000,468000001020030001,1963-06-10,NaN,1,영업/정상,0000,...,2023-09-01 10:06:43,U,2023-09-03 02:40:00,NaN,194930.133816,278364.263207,동물병원,NaN,000,0.0
5133,5134,동물병원,02_03_01_P,4690000,469000001019630001,1963-02-10,NaN,1,영업/정상,0000,...,2011-10-30 16:56:37,I,2018-08-31 23:59:59,NaN,200208.405929,233109.881474,동물병원,NaN,000,NaN
5134,5135,동물병원,02_03_01_P,3260000,326000001019580001,1958-06-01,NaN,1,영업/정상,0000,...,2012-02-07 09:13:32,I,2018-08-31 23:59:59,NaN,384448.822848,179719.355077,동물병원,NaN,000,NaN
5135,5136,동물병원,02_03_01_P,4980000,498000001019570001,1957-04-02,NaN,1,영업/정상,0000,...,2019-05-17 15:32:41,U,2019-05-19 02:40:00,NaN,179946.349298,199338.124221,동물병원,NaN,000,NaN

In [6]:
df.columns

Index(['번호', '개방서비스명', '개방서비스아이디', '개방자치단체코드', '관리번호', '인허가일자', '인허가취소일자',
       '영업상태구분코드', '영업상태명', '상세영업상태코드', '상세영업상태명', '폐업일자', '휴업시작일자', '휴업종료일자',
       '재개업일자', '소재지전화', '소재지면적', '소재지우편번호', '소재지전체주소', '도로명전체주소', '도로명우편번호',
       '사업장명', '최종수정시점', '데이터갱신구분', '데이터갱신일자', '업태구분명', '좌표정보(X)', '좌표정보(Y)',
       '업무구분명', '상세업무구분명', '권리주체일련번호', '총직원수'],
      dtype='object')

In [8]:
df['사업장명']

0           행복튼튼동물병원
1             엘림동물병원
2       도담동물의료센터동물병원
3         네오펫동물메디컬센터
4          건강하게 동물병원
            ...
5131          덕산가축병원
5132           김동물병원
5133          칠보동물병원
5134          중앙동물병원
5135          장성동물병원
Name: 사업장명, Length: 5136, dtype: object

In [ ]:
https://map.naver.com/p?c=15.00,0,0,0,dh
https://map.kakao.com/

In [ ]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time

# Chrome 드라이버 경로 설정 (다운로드 받은 드라이버의 경로를 지정해야 합니다)
chrome_driver_path = '/path/to/chromedriver'

# Chrome 브라우저 열기
driver = webdriver.Chrome(executable_path=chrome_driver_path)

# 네이버 지도 접속
driver.get("https://map.naver.com/")

# 검색어 입력 (예: '서울역')
search_query = '서울역'
search_box = driver.find_element("id", "search-input")
search_box.clear()
search_box.send_keys(search_query)
search_box.send_keys(Keys.RETURN)

# 페이지 로딩 대기 (원하는 요소가 로딩될 때까지 기다릴 수 있습니다)
time.sleep(2)

# 주소 정보 가져오기
address_element = driver.find_element("css selector", ".addr")
address = address_element.text

print(f"검색어 '{search_query}'의 주소: {address}")

# 브라우저 닫기
driver.quit()